[package]
name = "programming_bitcoin_in_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
primitive-types = "0.11.1"
sha2 = "0.10.2"
rand = "0.8.5"
